### ISSUE TITLE
플리킹 멈춤현상에 관해서 말씀드려요

### ISSUE THREAD

**Issue by kjs8584** [dohoons/jquery.touchSlider#1]
안녕하세요.
플리킹 잘쓰고 있는 유저 중 1명입니다.

플리킹이 가끔 멈춤현상이 발생하더라구여.

테스트하며 찾아보니 우연치않게 발견했습니다.

플리킹 영역에서 플리킹중 플리킹 영역이 아닌 곳에서 플리킹을 하면 플리킹이 멈춰버리는 현상이 있었습니다. 

아래 스크린샷은 테스트 결과 스크린샷입니다.
![screenshot_20151214-120939](https://cloud.githubusercontent.com/assets/16282979/11772092/22342080-a25c-11e5-998d-5f639193830b.png)

**Comment by dohoons** [comment]
해당 문제 확인하여 수정버전 올려놨습니다.
확인해보세요~

**Comment by kjs8584** [comment]
정말 감사합니다!!!

**Comment by kjs8584** [comment]
도훈님 멈춤현상 수정소스에서 다시 멀티터치가 되는거 같습니다 ㅠㅠ...

왼손으로 플리킹 중에 오른손으로 터치하면 페이지가 이상하게 이동이됩니다.

touchend 에 아래처럼 되어있으면 멈춤현상이 일어나고 멀티터치는 방지되는 방면
e.type == "touchend" && e.originalEvent.touches.length < 1
아래 처럼 되어있으면 멈춤현상은 사라지고 멀티터치가 되는거 같습니다.
e.type == "touchend"

**Comment by dohoons** [comment]
고친 문제가 또 발생했군요..
다시 수정해서 올렸습니다.

**Comment by kjs8584** [comment]
수정된걸로 테스트해봤는데.. 아직 그대로입니다 ㅠㅠ

플리킹중에 반대편 터치하면 막 움직이더라구여...

**Comment by dohoons** [comment]
이전처럼 멀티터치시 빈공간이 보이는 문제는 안생기는 것 같은데
반대편 터치해서 움직이는게 문제인건가요?

**Comment by kjs8584** [comment]
왼쪽으로 플리킹하면서 손은 떼지 않구여
그상태에서 동그라미부분에 터치를 하면 화면이 변합니다.
계속 터치시 왔다갔다 하게 됩니다.
![screenshot_20151214-120939](https://cloud.githubusercontent.com/assets/16282979/11775920/60455d42-a286-11e5-9146-bc35f47b69cd.png)

**Comment by dohoons** [comment]
음..부자연스럽긴 하네요.
좀 더 연구해봐야겠습니다.

**Comment by kjs8584** [comment]
touchend : function (e) {
            if((e.type == "touchend" && e.originalEvent.touches.length < 1) || e.type == "dragend") {

예전 e.originalEvent.touches.length < 1 때문인거 같긴한데... 저도 수정방안을 찾아보겠습니다. ㅠㅠ

도와주셔서 매번 감사합니다.
