### ISSUE TITLE
파일에 기능을 추가 해보았습니다.

### ISSUE THREAD

**Issue by dstyle0210** [dohoons/jquery.touchSlider#2]
일부 기능에 대하여 개선(?)을 해보았습니다.^^;;;
혹시라도 부끄럽지만, 도움되시는 부분이 있으시다면, marge진행하면 좋을거 같습니다.^^

"jquery 2.1.4" 로 적용.
autoplay , interval 옵션 추가적용
autoplay : {boolean} 기본값 false : 자동 플레이 적용
interval : {millsecend , number} 기본값 3000 : 자동플레이시 간격
"resize:true" 일 경우, 플리킹 외에 window.resize가 발생해도 height값이 자동적용.

경로
https://github.com/dstyle0210/jquery.touchSlider

**Comment by dohoons** [comment]
안녕하세요 . 
우선 미흡한 코드에 기능개선을 해주셔서 감사합니다.

jquery 버전 문제는 아직은 조금 조심스러워요..
오래전부터 사용중인 사이트도 있어서 1.4.x ~ 1.8.3 까지 고려하였고
한국의 실무자들을 위해 아직 IE7+ 기준으로 생각중입니다.
이번 계기로 고민을 해봐야겠습니다.

autoplay 에 대해서 기능추가 문의가 있었는데
기능을 사용하는 방법의 고민이 좀 있습니다. 
나중에 참고하여 추가하도록 하겠습니다.

resize 는 기존에 onresize 때에도 counter 함수가 돌기 때문에 
다른곳에서 추가로 height 를 조정하지 않아도 됩니다.

감사합니다.

**Comment by dstyle0210** [comment]
분명히 제가 만든 부분들이 요청이 있었을거라고 생각은 했지만, 사유들이 있었네요.ㅎㅎ
도훈님의 의견을 존중하겠습니다.^^
