### ISSUE TITLE
init시 view옵션과 실제 아이템 갯수가 일치할 경우 오류

### ISSUE THREAD

**Issue by qarty1** [dohoons/jquery.touchSlider#4]
초기화시에
view옵션과 list의 아이템수가 일치할 경우 stackoverflow가 납니다.
확인한 결과 

init 함수 내부의 if(this._len / this._view <= 1) 조건 부분에서 this.opts.roll를  false로 만들어 주고 있고
resize에서 default옵션과 비교하여 roll부분이 달라져서 init호출
여기서 다시 this.oprs.roll을 false만들고
resize에서 다시 roll 달라진 부분을 체크하여 init ...

이렇게 진행되는것 같습니다.
사용한 옵션은

$("#touch").touchSlider({
			page: 1,
			speed:500,
			view: 5,
			gap: 26,
			controls: false,
			btn_prev: $(".ts-controls.new .ts-prev-n"),
			btn_next: $(".ts-controls.new .ts-next-n"),
			paging:false,
			autoplay: {
				enable: false
			},
			breakpoints: {
				1024: {
					gap: 20,
					view: 3,
				},
				640: {
					gap: 14,
					view: 2,
				}
			}
		});

위와 같구요.
초기 페이지 로딩시 ul>li의 아이템이 5입니다.
지금도 보실지 모르겠지만.. 확인차 남깁니다.

**Comment by dohoons** [comment]
안녕하세요 오류 제보 정말 감사합니다.
roll 옵션이 사용될 수 있는 지 체크하는 방법으로 
오류 수정해서 1.6.10 버전 배포했습니다.
감사합니다.
