### ISSUE TITLE
최신버전 크롬에서 내부에 a 태그 클릭 안먹는 이슈

### ISSUE THREAD

**Issue by qarty1** [dohoons/jquery.touchSlider#5]
최근까지 잘 동작했었는데
크롬 업데이트가 된건지?
어느시점 이후로부터 touchSlider 내부에 a태그가 있는 경우 기본 이벤트가 먹지 않는 현상이 있습니다.
(클릭시 a태그 href 이동되지 않고 touchSlider의 touch 이벤트가 먹는듯 합니다)
여러번 광클을 하다보면 a태그 이벤트가 먹긴 하는데 잘 안되네요.

Chrome 빌드 : 90.0.4430.212
IE Edge 빌드 :  90.0.818.62
둘다 잘 안됩니다.

IE11에서는 잘 동작하네요.

**Comment by dohoons** [comment]
제가 크롬 90.0.4430.212 에서 a 태그를 넣고 테스트해봤는데 링크가 잘 되고 있는데요~
문제 확인할 수 있는 링크가 있을까요?

**Comment by qarty1** [comment]
![image](https://user-images.githubusercontent.com/36142733/118828476-455c2900-b8f8-11eb-8ac5-aebbafc338e2.png)

로컬 테스트중이라 올릴수가 없네요
데모페이지에서 임시로 테스트 해봤는데 저렇게 했을때(오른쪽 개발자도구 참조)
안되는 문제가 있었습니다
정확히는 ul > li > a 네요.

**Comment by dohoons** [comment]
이상하네요. 같은 부분에 똑같이 해봤는데 링크 동작이 잘 됩니다.
그러면 확장프로그램 문제일수도 있겠다 싶은데.. 시크릿모드로 한번 확인해보시겠어요?

**Comment by qarty1** [comment]
> 이상하네요. 같은 부분에 똑같이 해봤는데 링크 동작이 잘 됩니다.
> 그러면 확장프로그램 문제일수도 있겠다 싶은데.. 시크릿모드로 한번 확인해보시겠어요?

어오.. 신기하네요 저는 시크릿 모드에서 사용해도 같은 증상입니다
(클릭시 슬라이더가 미세하게 움직이는듯 하면서 클릭 이벤트 대신 슬라이더 이벤트가 먹음)
좀더 확인해보고 케이스를 보고드릴게요.

**Comment by qarty1** [comment]
완전 기본 기능만 넣은 js피들 링크입니다.
https://jsfiddle.net/26ems794/

저는 여기서도 잘 안되는데.. 한번 해보시겠어요?

**Comment by dohoons** [comment]
피들 링크에서 테스트 영상 올립니다.
처음에 js 초기화되기 전에 누른 경우 외에는 대체로 잘 되네요.

https://user-images.githubusercontent.com/5266928/119004852-e1099a00-b9c9-11eb-8b63-15f2e5fc390d.mov

**Comment by qarty1** [comment]
케이스를 찾았습니다.
그런데.. 참 뭐라 말씀드려야 할지..
이클립스가 켜져있을때만 그런 현상이 있습니다.
어찌됐던 라이브러리 문제는아닌데
정말 기상천외하네요.
이 이슈는 닫으셔도 될것 같습니다 ㅠ.ㅠ

https://user-images.githubusercontent.com/36142733/119007175-f67fc380-b9cb-11eb-9763-afab872c37e4.mp4

**Comment by dohoons** [comment]
아.. 이클립스가 브라우저나 마우스에 영향을 주나보군요.
어쩐일인지 찾아봐도 정보가 잘 안나오네요.
신기한 현상이라 궁금하긴 한데.. 일단 이슈는 클로즈하겠습니다.
추가 정보가 발견되면 알려주시면 좋겠습니다.
제보 감사합니다.
